### ISSUE TITLE
Plugin won't load, null reference.

### ISSUE THREAD

**Issue by sleepyspider1** [Ant-f/WorkingFilesList#12] opened 2017-08-16 17:02 UTC
here's the activity log. My guess is a file in the list was deleted or something.

  <entry>
    <record>592</record>
    <time>2017/08/16 16:58:45.488</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [WorkingFilesWindowPackage]Source: &apos;WorkingFilesList.ToolWindow&apos; Description: Object reference not set to an instance of an object.&#x000D;&#x000A;System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at WorkingFilesList.ToolWindow.ViewModel.DocumentMetadataManager.Synchronize(Documents documents, Boolean setUsageOrder)&#x000D;&#x000A;   at WorkingFilesList.WorkingFilesWindowPackage.InitializeServices(IKernel kernel, IOptionsPageService optionsPageService) in F:\Visual Studio Projects\WorkingFilesList\Solution\WorkingFilesList\WorkingFilesWindowPackage.cs:line 124&#x000D;&#x000A;   at WorkingFilesList.WorkingFilesWindowPackage.Initialize() in F:\Visual Studio Projects\WorkingFilesList\Solution\WorkingFilesList\WorkingFilesWindowPackage.cs:line 100&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)</description>
    <guid>{26BF5782-13D2-4168-B979-BFCDE9BD63DD}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>593</record>
    <time>2017/08/16 16:58:45.489</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [WorkingFilesWindowPackage](null)</description>
    <guid>{26BF5782-13D2-4168-B979-BFCDE9BD63DD}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>594</record>
    <time>2017/08/16 16:58:45.491</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [WorkingFilesWindowPackage]</description>
    <guid>{26BF5782-13D2-4168-B979-BFCDE9BD63DD}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by Ant-f** [comment] 2017-08-16 19:39
Hi

When the plugin loads, it tries to get a list of all open documents to populate the tool window; it does this by trying to getting an instance of the Visual Studio automation model, and querying its Documents.

From looking at the stack trace provided, the error could possibly be caused by being unable to get an instance of the automation model for some reason. Is this the first time that you've tried running the plugin, or was it running ok previously?

If the latter, is it possible that a recent update of Visual Studio/another plugin modified something: maybe you could try uninstalling Working Files List and re-installing it?

If this is the first time that you've tried to use Working Files List, which version of Visual Studio are you running, and is it the latest Update version?

**Comment by Ant-f** [comment] 2017-08-30 16:21
It's been 14 days since this was raised, and no further details have been provided. I'm going to assume that this is no longer a problem; closing issue.

**Closed by Ant-f** 2017-08-30 16:21 UTC
