### ISSUE TITLE
suggestion - Pin file across visual studio sessions

### ISSUE THREAD

**Issue by marco2250** [Ant-f/WorkingFilesList#27] opened 2019-10-31 14:53 UTC
This plugin is great and promises a lot. Thank you and congratulations for the great job!

I would love to be able to be able to pin a file and keep it on the list even if I close the file in visual studio editor, even if I close and re-open visual studio.

That would be useful with files that I tent to work from time to time.

Thank you.

**Comment by Ant-f** [comment] 2019-10-31 17:24
Hi Marco

Thanks for using Working Files List; glad you like it. If I understand your question correctly, you should be able to do this already. See here for more info:

https://github.com/Ant-f/WorkingFilesList/wiki/User-Guide#pinned-items

The documentation is a little old: pinned items are persisted when the solution is closed/reopened as of version 1.4

**Comment by marco2250** [comment] 2019-10-31 17:44
Thank you for your answer, but my request is bit different.

I want to be able to CLOSE the file and keep it pinned...

Thank you

**Comment by Ant-f** [comment] 2019-10-31 18:03
Sorry, I may be missing something. When I pin a file by either:

* Double-clicking the item in Working Files List
* Click the pin button that appears on the right of an item in Working Files List on mouse-over

it appears in the top part of Working Files List. I can then close the file in Visual Studio by any of the following methods:

* Close it from the Visual Studio text editor tab
* Click the 'x' button that appears on the right of an item in Working Files List on mouse-over
* Middle click an item in Working Files List

For me in all three scenarios, the editor is closed in Visual Studio, and the item in the bottom part of Working Files List disappears. However, the pinned item at the top of Working Files List remains there. Do the pinned items disappear when you close the file?

**Comment by marco2250** [comment] 2019-10-31 18:46
No problem!

The fact is that when I close a pinned file, it's removed from "Working Files List".

What I would like is to keep it on "Working Files List", even though I closed it in Visual Studio or even if I close and re-open visual studio.

Explaining: There are files that I tend to work from time to time and it would be useful to be able to open them more easily.

Thank you

**Comment by Ant-f** [comment] 2019-10-31 20:04
I've just created a new console app that has two classes: `class1.cs` and `class2.cs`. I have both classes open and have pinned `class1.cs` by double-clicking it. Working Files List looks like this:

![WorkingFilesListClass1Open](https://user-images.githubusercontent.com/1225020/67981175-f6687900-fc17-11e9-84a6-9d4c3f1954f4.png)

You can see that `class1.cs` (highlighted in yellow) appears twice: the one above is where pinned items appear. The one below is in the list of all open files. When I close the editor for `class1.cs` in Visual Studio, Working Files List looks like this:

![WorkingFilesListClass1Closed](https://user-images.githubusercontent.com/1225020/67981301-3a5b7e00-fc18-11e9-9642-bef030a1b365.png)

`class1.cs` (highlighted in yellow) now only appears once: in the above section, where pinned items appear. As `class1.cs` has been closed, it no longer appears in the section for open files (as shown in the first image).

Unless I have misunderstood something, the functionality you're asking for already exists

**Comment by marco2250** [comment] 2019-10-31 20:16
Please, check enclosed video showing it's not working for me, vstd 2019.

Thank you!!!

**Comment by Ant-f** [comment] 2019-10-31 20:20
Sorry, I can't find a link to the video.

Also, which version of Working Files List are you using?

Thanks

**Comment by marco2250** [comment] 2019-10-31 20:31
The latest one (downloaded it today).

Link to video:
http://www.ticow.com.br/files/media/2019-10-31_17-12-31.zip

**Comment by Ant-f** [comment] 2019-10-31 20:59
Thanks for the video. It seems the problem is that pinning does not work when using files that are not part of a Visual Studio project (e.g. opening individual files). This may require a bit more thought and investigation, when I have a bit more time.

Pinning does work when used with files that are part of a Solution and Project though.

**Comment by marco2250** [comment] 2019-10-31 21:00
I understand. Thank you for all your help!

How can I add a feature request (I'm new to github)

**Comment by Ant-f** [comment] 2019-10-31 21:13
I've created a new issue, with a reference to this, and will close this to avoid confusion

**Closed by Ant-f** 2019-10-31 21:13 UTC
